### ISSUE TITLE
Update to 1.4.3

### ISSUE THREAD

**Issue by luispedro** [conda-forge/mahotas-feedstock#3]
FYI: Version 1.4.2 was just released (1 minute ago).

Should be a simple matter of updating the version string and the MD5 checksum as it's a minor release.

**Comment by luispedro** [comment]
1.4.2 had some packaging issues, so 1.4.3 was released (it's the same if you clone from github, but pypi was broken).

**Comment by jakirkham** [comment]
Thanks for the ping.

Am cleaning up the recipe format to match more recent expectations. Please see PR ( https://github.com/conda-forge/mahotas-feedstock/pull/4 ) to see what this means. Will bump the version after.

**Comment by jakirkham** [comment]
Oh, was going to ask what you mean by the PyPI release was broken with 1.4.2?

**Comment by luispedro** [comment]
There was a file missing from the source distribution: https://github.com/luispedro/mahotas/issues/79

**Comment by jakirkham** [comment]
Thanks for the clarification.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/mahotas-feedstock/pull/6 ) for the new release.

**Comment by jakirkham** [comment]
Reopening as I had to pull all of these packages. Apparently Travis CI has changed the default OS to 10.11. So we have to restrict it back to 10.9. Will try again one we have fixed that issue.

**Comment by jakirkham** [comment]
Fixing with PR ( https://github.com/conda-forge/mahotas-feedstock/pull/12 ).
